#ifndef RETORNOS
#define RETORNOS

typedef struct no No;

enum{
    ERROR_ITEMJAEXISTE,
    ERROR_MALLOC,
    ERROR_LISTAVAZIA,
    ERROR_NAOENCONTRADO,
    ERROR_INFO,
    ERROR_INVALIDOCPF,
    ERROR_ARQUIVONENCONTRADO,
    SUCESS_INCLUI,
    SUCESS_ENCONTRADO,
    SUCESS_ATUALIZA,
    SUCESS_DELETE,
    SUCESS_CPF,
    SUCESS,
};

#endif