#ifndef RETORNOS
#define RETORNOS

typedef struct no No;

enum{
    ERROR_ITEMJAEXISTE,
    ERROR_NAOALUGADO,
    ERROR_SOLICITARCOMPRA,
    ERROR_MALLOC,
    ERROR_LISTAVAZIA,
    ERROR_NAOENCONTRADO,
    ERROR_INFO,
    ERROR_SEMESTOQUE,
    ERROR_INVALIDOCPF,
    ERROR_LEITURA,
    ERROR_ESCRITA,
    ERROR_ARQUIVONEXISTE,
    ERROR_COMPRA,
    ERROR_SALDONEG,
    SUCESS_INCLUI,
    SUCESS_ENCONTRADO,
    SUCESS_ATUALIZA,
    SUCESS_DELETE,
    SUCESS_CPF,
    SUCESS_DEVOLUCAO,
    SUCESS_ALUGADO,
    SUCESS_ESCRITA,
    SUCESS,
};

#endif